clean-exits: update actions and save test results

diff --git a/.github/workflows/qa-clean-exit-snapshot-downloading.yml b/.github/workflows/qa-clean-exit-snapshot-downloading.yml
--- a/.github/workflows/qa-clean-exit-snapshot-downloading.yml
+++ b/.github/workflows/qa-clean-exit-snapshot-downloading.yml
@@ -22,26 +22,17 @@ jobs:
     runs-on: self-hosted
     env:
       ERIGON_DATA_DIR: ${{ github.workspace }}/erigon_data
+      ERIGON_QA_PATH: /home/qarunner/erigon-qa
       WORKING_TIME_SECONDS: 600
 
     steps:
     - name: Check out repository
-      uses: actions/checkout@v2
+      uses: actions/checkout@v4
 
     - name: Set up Go
       uses: actions/setup-go@v4
       with:
         go-version: '1.21'
-
-    - name: Set up Python
-      uses: actions/setup-python@v4
-      with:
-        python-version: '3.x'
-
-    #- name: Install dependencies
-    #  run: |
-    #    sudo apt-get update
-    #    sudo apt-get install -y build-essential make gcc
 
     - name: Clean Erigon Build Directory
       run: |
@@ -52,13 +43,19 @@ jobs:
         make erigon
       working-directory: ${{ github.workspace }}
 
+    - name: Pause the Erigon instance dedicated to db maintenance
+      run: |
+        curl -X POST -H "Accept: application/json" -d '{"status": "paused"}' http://localhost:8080/production/default/status || true
+
     - name: Run Erigon, send ctrl-c and check for clean exiting
       run: |
+        set +e # Disable exit on error
+        
         # Run Erigon, send ctrl-c and check logs
-        python3 ${{ github.workspace }}/../../../../erigon-qa/test_system/qa-tests/clean-exit/run_and_check_clean_exit.py ${{ github.workspace }}/build/bin $ERIGON_DATA_DIR $WORKING_TIME_SECONDS
+        python3 $ERIGON_QA_PATH/test_system/qa-tests/clean-exit/run_and_check_clean_exit.py ${{ github.workspace }}/build/bin $ERIGON_DATA_DIR $WORKING_TIME_SECONDS
   
         # Capture monitoring script exit status
-        monitoring_exit_status=$?
+        test_exit_status=$?
         
         # Clean up Erigon process if it's still running
         if kill -0 $ERIGON_PID 2> /dev/null; then
@@ -72,10 +69,36 @@ jobs:
         # Clean up Erigon build and data directories
         rm -rf $ERIGON_DATA_DIR
         
-        # Check monitoring script exit status
-        if [ $monitoring_exit_status -eq 0 ]; then
-          echo "Monitoring completed successfully"
+        # Check test runner script exit status
+        if [ $test_exit_status -eq 0 ]; then
+          echo "Tests completed successfully"
+          echo "TEST_RESULT=success" >> "$GITHUB_OUTPUT"
         else
-          echo "Error detected in Erigon logs or monitoring script exited unexpectedly"
-          exit 1
+          echo "Error detected during tests"
+          echo "TEST_RESULT=failure" >> "$GITHUB_OUTPUT"
         fi
+
+    - name: Resume the Erigon instance dedicated to db maintenance
+      run: |
+        curl -X POST -H "Accept: application/json" -d '{"status": "running"}' http://localhost:8080/production/default/status || true
+
+    - name: Save test results
+      if: always()
+      run: python3 $ERIGON_QA_PATH/test_system/uploads/upload_test_results.py --commit $(git rev-parse --short HEAD) --test_name clean-exit-snapshot-downloading --outcome steps.test_step.outputs.TEST_RESULT --result_file $ERIGON_QA_PATH/test_system/qa-tests/clean-exit/result.json
+
+    - name: Upload test results
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: test-results
+        path: $ERIGON_QA_PATH/test_system/qa-tests/tip-tracking/result.json
+
+    - name: Action for Success
+      if: steps.test_step.outputs.TEST_RESULT == 'success'
+      run: echo "::notice::Tests completed successfully"
+
+    - name: Action for Not Success
+      if: steps.test_step.outputs.TEST_RESULT != 'success'
+      run: |
+        echo "::error::Error detected during tests"
+        exit 1
