avoid using the deprecated set-output; add a warning if the failure is due to the infrastructure

diff --git a/.github/workflows/qa-rpc-integration-tests-polygon.yml b/.github/workflows/qa-rpc-integration-tests-polygon.yml
--- a/.github/workflows/qa-rpc-integration-tests-polygon.yml
+++ b/.github/workflows/qa-rpc-integration-tests-polygon.yml
@@ -105,7 +105,7 @@ jobs:
           test_exit_status=$?
           
           # Save the subsection reached status
-          echo "::set-output name=test_executed::true"
+          echo "test_executed=true" >> $GITHUB_OUTPUT
           
           # Check test runner exit status
           if [ $test_exit_status -eq 0 ]; then
@@ -156,6 +156,14 @@ jobs:
           
           python3 $ERIGON_QA_PATH/test_system/qa-tests/uploads/upload_test_results.py --repo erigon --commit $(git rev-parse HEAD) --branch ${{ github.ref_name }} --test_name rpc-integration-tests --chain $CHAIN --runner ${{ runner.name }} --db_version $db_version --outcome $TEST_RESULT #--result_file ${{ github.workspace }}/result-$CHAIN.json
 
+      - name: Action to check failure condition
+        if: failure()
+        run: |
+          if [ "${{ steps.test_step.outputs.test_executed }}" != "true" ]; then
+            echo "::warning::Test not executed, workflow failed for infrastructure reasons"
+          fi
+          #exit 1
+          
       - name: Action for Success
         if: steps.test_step.outputs.TEST_RESULT == 'success'
         run: echo "::notice::Tests completed successfully"
