integrate with block downloader v2

diff --git a/.github/workflows/qa-rpc-integration-tests.yml b/.github/workflows/qa-rpc-integration-tests.yml
--- a/.github/workflows/qa-rpc-integration-tests.yml
+++ b/.github/workflows/qa-rpc-integration-tests.yml
@@ -11,28 +11,35 @@ on:
       - main
       - 'release/3.*'
     types:
+      - opened
+      - reopened
+      - synchronize
       - ready_for_review
 
+
 jobs:
-  integration-test-suite:
-    runs-on: [ self-hosted, qa, RpcSpecific ]
+  mainnet-rpc-integ-tests:
+    if: false # temporarily disabled after PR 15838
+    concurrency:
+      group: >-
+        ${{
+          (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) && 
+          format('{0}-{1}', github.workflow, github.run_id) ||
+          format('{0}-{1}', github.workflow, github.ref)
+        }}
+      cancel-in-progress: true
+    runs-on: [ self-hosted, qa, Ethereum, rpc-integration ]
     env:
       ERIGON_REFERENCE_DATA_DIR: /opt/erigon-versions/reference-version/datadir
       ERIGON_TESTBED_AREA: /opt/erigon-testbed
       ERIGON_QA_PATH: /home/qarunner/erigon-qa
+      ERIGON_ASSERT: true
       RPC_PAST_TEST_DIR: /opt/rpc-past-tests
       CHAIN: mainnet
 
     steps:
       - name: Check out repository
         uses: actions/checkout@v4
-
-      - name: Checkout RPC Tests Repository & Install Requirements
-        run: |
-          rm -rf ${{ runner.workspace }}/rpc-tests
-          git -c advice.detachedHead=false clone --depth 1 --branch remove_aura_fields_from_mainnet https://github.com/erigontech/rpc-tests ${{runner.workspace}}/rpc-tests
-          cd ${{ runner.workspace }}/rpc-tests
-          pip3 install -r requirements.txt
 
       - name: Clean Erigon Build Directory
         run: |
@@ -64,6 +71,7 @@ jobs:
           RPC_DAEMON_PID=$!          
           RPC_DAEMON_EXIT_STATUS=$?
           echo "RPC_DAEMON_PID=$RPC_DAEMON_PID" >> $GITHUB_ENV
+          echo "rpc_daemon_started=true" >> $GITHUB_OUTPUT
           
           sleep 5
           tail erigon.log
@@ -94,40 +102,34 @@ jobs:
       - name: Run RPC Integration Tests
         id: test_step
         run: |
-          set +e # Disable exit on error
           commit=$(git -C ${{runner.workspace}}/erigon rev-parse --short HEAD)
+          TEST_RESULT_DIR="$RPC_PAST_TEST_DIR/mainnet_$(date +%Y%m%d_%H%M%S)_integration_${commit}_http/"
+          echo "TEST_RESULT_DIR=$TEST_RESULT_DIR" >> $GITHUB_ENV
 
-          cd ${{ runner.workspace }}/rpc-tests/integration
-          rm -rf ./mainnet/results/
-                    
-          # Run RPC integration test runner via http
-          chmod +x ${{ runner.workspace }}/erigon/.github/workflows/scripts/run_rpc_tests.sh
-          ${{ runner.workspace }}/erigon/.github/workflows/scripts/run_rpc_tests.sh
+          chmod +x ${{ runner.workspace }}/erigon/.github/workflows/scripts/run_rpc_tests_ethereum.sh
           
-          # Capture test runner script exit status
-          test_exit_status=$?
-          
-          # Save the subsection reached status
+          set +e # Disable exit on error for test run
+          ${{ runner.workspace }}/erigon/.github/workflows/scripts/run_rpc_tests_ethereum.sh ${{ runner.workspace }} $TEST_RESULT_DIR
+          test_exit_status=$? # Capture test runner script exit status
+          set -e # Re-enable exit on error after test run
+
           echo "test_executed=true" >> $GITHUB_OUTPUT
-          
-          # Check test runner exit status
+
+          echo
           if [ $test_exit_status -eq 0 ]; then
-            echo "tests completed successfully"
-            echo
+            echo "RPC tests completed successfully"
             echo "TEST_RESULT=success" >> "$GITHUB_OUTPUT"
           else
-            echo "error detected during tests"
+            echo "Error detected during RPC tests"
             echo "TEST_RESULT=failure" >> "$GITHUB_OUTPUT"
-          
-            # Save failed results to a directory with timestamp and commit hash
-            cp -r ${{ runner.workspace }}/rpc-tests/integration/mainnet/results/ $RPC_PAST_TEST_DIR/mainnet_$(date +%Y%m%d_%H%M%S)_integration_$commit_http/
           fi
 
       - name: Stop Erigon RpcDaemon
+        if: always()
         working-directory: ${{ github.workspace }}/build/bin
         run: |
           # Clean up rpcdaemon process if it's still running
-          if kill -0 $RPC_DAEMON_PID 2> /dev/null; then
+          if [ -n "$RPC_DAEMON_PID" ] && kill -0 $RPC_DAEMON_PID 2> /dev/null; then
             echo "RpcDaemon stopping..."
             kill $RPC_DAEMON_PID
             echo "RpcDaemon stopped"
@@ -154,7 +156,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: test-results
-          path: ${{ runner.workspace }}/rpc-tests/integration/mainnet/results/
+          path: ${{ env.TEST_RESULT_DIR }}
 
       - name: Save test results
         if: steps.test_step.outputs.test_executed == 'true'
