update workflows with changes in main

diff --git a/.github/workflows/qa-rpc-integration-tests-latest.yml b/.github/workflows/qa-rpc-integration-tests-latest.yml
--- a/.github/workflows/qa-rpc-integration-tests-latest.yml
+++ b/.github/workflows/qa-rpc-integration-tests-latest.yml
@@ -34,7 +34,7 @@ jobs:
     runs-on: [ self-hosted, qa, Ethereum, rpc-latest-erigon ]
     env:
       ERIGON_REFERENCE_DATA_DIR: /opt/erigon-versions/reference-version/datadir
-      ERIGON_TESTBED_AREA: /opt/erigon-testbed
+      ERIGON_TESTBED_DATA_DIR: /opt/erigon-testbed/datadir
       ERIGON_QA_PATH: /home/qarunner/erigon-qa
       TOTAL_TIME_SECONDS: 900 # 15 minutes
       REFERENCE_SYSTEM_HOST_ADDRESS: 157.180.55.78:8545
@@ -44,7 +44,7 @@ jobs:
 
     steps:
       - name: Check out repository
-        uses: actions/checkout@v5
+        uses: actions/checkout@v6
 
       - name: Clean Erigon Build Directory
         run: |
@@ -59,18 +59,23 @@ jobs:
         run: |
           python3 $ERIGON_QA_PATH/test_system/db-producer/pause_production.py || true
 
-      - name: Save Erigon Chaindata Directory
-        id: save_chaindata_step
+      - name: Save Erigon datadir Directory
+        id: save_datadir_step
         run: |
-          rm -rf $ERIGON_TESTBED_AREA/chaindata-prev || true
-          echo "Backup chaindata"
-          cp -r $ERIGON_REFERENCE_DATA_DIR/chaindata $ERIGON_TESTBED_AREA/chaindata-prev
+          rm -rf $ERIGON_TESTBED_DATA_DIR || true
+
+          echo "Mirror datadir"
+          if ! "$GITHUB_WORKSPACE/cmd/scripts/mirror-datadir.sh" "$ERIGON_REFERENCE_DATA_DIR" "$ERIGON_TESTBED_DATA_DIR" > /dev/null 2>&1; then
+            echo "Failed to mirror datadir from $ERIGON_REFERENCE_DATA_DIR to $ERIGON_TESTBED_DATA_DIR"
+            exit 1
+          fi
+          echo "datadir_saved=true" >> $GITHUB_OUTPUT
 
       - name: Run Migrations
         working-directory: ${{ github.workspace }}/build/bin
         run: |
           echo "Running migrations on datadir..."
-          ./integration run_migrations --datadir $ERIGON_REFERENCE_DATA_DIR --chain $CHAIN
+          ./integration run_migrations --datadir $ERIGON_TESTBED_DATA_DIR --chain $CHAIN
 
       - name: Run Erigon version and wait for sync 
         id: pre_test_step
@@ -80,7 +85,7 @@ jobs:
           # Launch the testbed Erigon instance & test its ability to sync 
           python3 $ERIGON_QA_PATH/test_system/qa-tests/tip-sync/run_and_chase_tip.py \
             --build-dir=${{ github.workspace }}/build/bin \
-            --data-dir=$ERIGON_REFERENCE_DATA_DIR \
+            --data-dir=$ERIGON_TESTBED_DATA_DIR \
             --total-time=$TOTAL_TIME_SECONDS \
             --chain=$CHAIN \
             --node-type=minimal_node \
@@ -106,7 +111,7 @@ jobs:
         id: test_step
         run: |
           commit=$(git -C ${{runner.workspace}}/erigon rev-parse --short HEAD)
-          TEST_RESULT_DIR="$RPC_PAST_TEST_DIR/mainnet_$(date +%Y%m%d_%H%M%S)_integration_${commit}_http/"
+          TEST_RESULT_DIR="$RPC_PAST_TEST_DIR/mainnet_$(date +%Y%m%d_%H%M%S)_integration_${commit}_http"
           echo "TEST_RESULT_DIR=$TEST_RESULT_DIR" >> $GITHUB_ENV
 
           DUMP_RESPONSE=""
@@ -132,7 +137,31 @@ jobs:
             echo "TEST_RESULT=failure" >> "$GITHUB_OUTPUT"
           fi
 
-      - name: Stop Erigon 
+      - name: Generate Summary
+        if: always() && steps.test_step.outputs.test_executed == 'true'
+        run: |
+          SUMMARY_FILE="${{ env.TEST_RESULT_DIR }}/summary.md"
+          LOG_FILE="${{ env.TEST_RESULT_DIR }}/output.log"
+
+          cat << 'EOF' > $SUMMARY_FILE
+          # ${{ github.workflow }} Report
+
+          ## Test Configuration
+          - **Chain:** ${{ env.CHAIN }}
+          - **Result:** ${{ steps.test_step.outputs.TEST_RESULT }}
+
+          ## Test Output
+          ```
+          EOF
+
+          cat $LOG_FILE >> $SUMMARY_FILE
+
+          echo '```' >> $SUMMARY_FILE
+
+          cat $SUMMARY_FILE
+          cat $SUMMARY_FILE >> $GITHUB_STEP_SUMMARY
+
+      - name: Stop Erigon
         if: always()
         run: |
           # the erigon pid is stored in erigon.pid file
@@ -147,28 +176,14 @@ jobs:
             echo "Erigon has already terminated"
           fi
 
-      - name: Restore Erigon Chaindata Directory
-        if: ${{ always() }}
-        run: |
-          if [ -d "$ERIGON_TESTBED_AREA/chaindata-prev" ] && [ "${{ steps.save_chaindata_step.outcome }}" == "success" ]; then
-          rm -rf $ERIGON_REFERENCE_DATA_DIR/chaindata
-          echo "Restore chaindata"
-          mv $ERIGON_TESTBED_AREA/chaindata-prev $ERIGON_REFERENCE_DATA_DIR/chaindata
-          fi
-
-      - name: Resume the Erigon instance dedicated to db maintenance
-        if: ${{ always() }}
-        run: |
-          python3 $ERIGON_QA_PATH/test_system/db-producer/resume_production.py || true
-
       - name: Upload test results
         if: steps.test_step.outputs.test_executed == 'true'
-        uses: actions/upload-artifact@v5
+        uses: actions/upload-artifact@v6
         with:
           name: test-results
           path: |
             ${{ env.TEST_RESULT_DIR }}
-            ${{ env.ERIGON_REFERENCE_DATA_DIR }}/logs/
+            ${{ env.ERIGON_TESTBED_DATA_DIR }}/logs/
 
       - name: Save test results
         if: steps.test_step.outputs.test_executed == 'true'
@@ -182,6 +197,18 @@ jobs:
           fi
           
           python3 $ERIGON_QA_PATH/test_system/qa-tests/uploads/upload_test_results.py --repo erigon --commit $(git rev-parse HEAD) --branch ${{ github.ref_name }} --test_name rpc-integration-tests --chain $CHAIN --runner ${{ runner.name }} --db_version $db_version --outcome $TEST_RESULT #--result_file ${{ github.workspace }}/result-$CHAIN.json
+
+      - name: Delete Erigon Testbed Data Directory
+        if: ${{ always() && steps.save_datadir_step.outputs.datadir_saved == 'true' }}
+        run: |
+          if [ -d "$ERIGON_TESTBED_DATA_DIR" ]; then
+            rm -rf $ERIGON_TESTBED_DATA_DIR
+          fi
+
+      - name: Resume the Erigon instance dedicated to db maintenance
+        if: ${{ always() }}
+        run: |
+          python3 $ERIGON_QA_PATH/test_system/db-producer/resume_production.py || true
 
       - name: Action to check failure condition
         if: failure()
