refactor one-liner for Gnosis RPC Integration Tests

diff --git a/.github/workflows/qa-rpc-integration-tests.yml b/.github/workflows/qa-rpc-integration-tests.yml
--- a/.github/workflows/qa-rpc-integration-tests.yml
+++ b/.github/workflows/qa-rpc-integration-tests.yml
@@ -106,10 +106,10 @@ jobs:
           echo "TEST_RESULT_DIR=$TEST_RESULT_DIR" >> $GITHUB_ENV
 
           chmod +x ${{ runner.workspace }}/erigon/.github/workflows/scripts/run_rpc_tests_ethereum.sh
+          
           set +e # Disable exit on error for test run
           ${{ runner.workspace }}/erigon/.github/workflows/scripts/run_rpc_tests_ethereum.sh ${{ runner.workspace }} $TEST_RESULT_DIR
-          # Capture test runner script exit status
-          test_exit_status=$?
+          test_exit_status=$? # Capture test runner script exit status
           set -e # Re-enable exit on error after test run
 
           echo "test_executed=true" >> $GITHUB_OUTPUT
