add downgrade tip-tracking test

diff --git a/.github/workflows/qa-tip-tracking.yml b/.github/workflows/qa-tip-tracking.yml
--- a/.github/workflows/qa-tip-tracking.yml
+++ b/.github/workflows/qa-tip-tracking.yml
@@ -18,7 +18,7 @@ jobs:
       ERIGON_REFERENCE_DATA_DIR: /opt/erigon-versions/reference-version-3.0/datadir
       ERIGON_TESTBED_DATA_DIR: /opt/erigon-testbed/datadir
       ERIGON_QA_PATH: /home/qarunner/erigon-qa
-      TRACKING_TIME_SECONDS: 14400 # 4 hours
+      TRACKING_TIME_SECONDS: 7200 # 2 hours
       TOTAL_TIME_SECONDS: 28800 # 8 hours
       CHAIN: mainnet
 
@@ -44,6 +44,8 @@ jobs:
       run: |
         rsync -a --delete $ERIGON_REFERENCE_DATA_DIR/ $ERIGON_TESTBED_DATA_DIR/
 
+    # Upgrade + tip-tracking test
+
     # Uncomment the following lines if you need to run the datadir upgrade procedure explicitly
     # For now, it is executed automatically by erigon when it detects the old format.
     #- name: Run the datadir upgrade procedure
@@ -56,9 +58,7 @@ jobs:
       run: |
         set +e # Disable exit on error
         
-        # 1. Launch the testbed Erigon instance
-        # 2. Allow time for the Erigon to achieve synchronization
-        # 3. Begin timing the duration that Erigon maintains synchronization
+        # Launch the testbed Erigon instance & test its ability to maintain sync
         python3 $ERIGON_QA_PATH/test_system/qa-tests/tip-tracking/run_and_check_tip_tracking.py \
           ${{ github.workspace }}/build/bin $ERIGON_TESTBED_DATA_DIR $TRACKING_TIME_SECONDS $TOTAL_TIME_SECONDS Erigon3 $CHAIN
   
@@ -77,10 +77,12 @@ jobs:
 
         # Check test runner script exit status
         if [ $test_exit_status -eq 0 ]; then
-          echo "Tests completed successfully"
+          echo "Upgrade & tip-tracking test completed successfully"
+          echo "::notice::Upgrade & tip-tracking test completed successfully"
           echo "TEST_RESULT=success" >> "$GITHUB_OUTPUT"
         else
-          echo "Error detected during tests"
+          echo "Upgrade & tip-tracking test encountered an error"
+          echo "::error::Upgrade & tip-tracking test encountered an error"
           echo "TEST_RESULT=failure" >> "$GITHUB_OUTPUT"
         fi
 
@@ -88,6 +90,7 @@ jobs:
       if: always()
       uses: actions/upload-artifact@v4
       with:
+        name: torrent-client-status
         path: torrent-client-status.txt
 
     - name: Save test results
@@ -132,6 +135,60 @@ jobs:
         name: metric-plots
         path: ${{ github.workspace }}/metrics-${{ env.CHAIN }}-plots*
 
+    # Downgrade + tip-tracking test
+
+    - name: Run the datadir downgrade procedure
+      working-directory: ${{ github.workspace }}
+      run: |
+        ./build/bin/erigon seg reset-to-old-ver-format --datadir $ERIGON_TESTBED_DATA_DIR
+
+    - name: Run previous Erigon version, wait sync and check ability to maintain sync
+      id: downgrade_test_step
+      run: |
+        set +e # Disable exit on error
+        
+        # Launch the testbed Erigon instance & test its ability to maintain sync
+        python3 $ERIGON_QA_PATH/test_system/qa-tests/tip-tracking/run_and_check_tip_tracking.py \
+          ${{ env.ERIGON_TESTBED_DATA_DIR }}/.. $ERIGON_TESTBED_DATA_DIR $TRACKING_TIME_SECONDS $TOTAL_TIME_SECONDS Erigon3 $CHAIN
+        
+        # Capture monitoring script exit status
+        test_exit_status=$?
+        
+        # Save the subsection reached status
+        echo "test_executed=true" >> $GITHUB_OUTPUT
+        
+        # Clean up Erigon process if it's still running
+        if kill -0 $ERIGON_PID 2> /dev/null; then
+          echo "Terminating Erigon"
+          kill $ERIGON_PID
+          wait $ERIGON_PID
+        fi
+
+        # Check test runner script exit status
+        if [ test_exit_status -eq 0 ]; then
+          echo "Downgrade & tip-tracking test completed successfully"
+          echo "::notice::Downgrade & tip-tracking test completed successfully"
+          echo "TEST_RESULT=success" >> "$GITHUB_OUTPUT"
+        else
+          echo "Downgrade tests encountered an error"
+          echo "::error::Downgrade & tip-tracking test encountered an error"
+          echo "TEST_RESULT=failure" >> "$GITHUB_OUTPUT"
+        fi
+
+    - name: Upload Downloader Torrent Client Status of the downgrade test
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: torrent-client-status-downgrade-test
+        path: torrent-client-status.txt
+
+    - name: Upload erigon log of the downgrade test
+      if: steps.downgrade_test_step.outputs.test_executed == 'true'
+      uses: actions/upload-artifact@v4
+      with:
+        name: erigon-log-downgrade-test
+        path: ${{ env.ERIGON_TESTBED_DATA_DIR }}/logs/erigon.log
+
     - name: Delete Erigon Testbed Data Directory
       if: ${{ always() }}
       run: |
@@ -144,12 +201,8 @@ jobs:
       run: |
         python3 $ERIGON_QA_PATH/test_system/db-producer/resume_production.py || true
 
-    - name: Action for Success
-      if: steps.test_step.outputs.TEST_RESULT == 'success'
-      run: echo "::notice::Tests completed successfully"
-
     - name: Action for Not Success
-      if: steps.test_step.outputs.TEST_RESULT != 'success'
+      if: steps.test_step.outputs.TEST_RESULT != 'success' || steps.downgrade_test_step.outputs.TEST_RESULT != 'success'
       run: |
         echo "::error::Error detected during tests"
         exit 1
