[r3.1] qa-tests: add upgrade/downgrade in Gnosis tip tracking

diff --git a/.github/workflows/qa-tip-tracking-gnosis.yml b/.github/workflows/qa-tip-tracking-gnosis.yml
--- a/.github/workflows/qa-tip-tracking-gnosis.yml
+++ b/.github/workflows/qa-tip-tracking-gnosis.yml
@@ -4,7 +4,13 @@ on:
   push:
     branches:
       - 'release/3.1'
-  workflow_dispatch:     # Run manually
+  workflow_dispatch: # Run manually
+    inputs:
+      explicit_upgrade:
+        description: 'If true, perform explicit upgrade steps (by default they happen automatically)'
+        type: boolean
+        required: false
+        default: false
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -39,15 +45,33 @@ jobs:
       run: |
         python3 $ERIGON_QA_PATH/test_system/db-producer/pause_production.py || true
 
-    - name: Restore Erigon Testbed Data Directory
+    - name: Restore Erigon Testbed Data Directory & Erigon binary
       id: save_chaindata_step
       run: |
         rsync -a --delete $ERIGON_REFERENCE_DATA_DIR/ $ERIGON_TESTBED_DATA_DIR/
+        cp $ERIGON_REFERENCE_DATA_DIR/../erigon $ERIGON_TESTBED_DATA_DIR/../
 
+    # Upgrade + tip-tracking test
+
+    - name: Print datadir contents before upgrade (for debugging)
+      if: ${{ inputs.explicit_upgrade }}
+      working-directory: ${{ github.workspace }}
+      run: |
+        find $ERIGON_TESTBED_DATA_DIR
+
+    # The following task runs the datadir upgrade procedure explicitly.
+    # It is unnecessary and is executed automatically by erigon when it detects the old format.
     - name: Run the datadir upgrade procedure
+      if: ${{ inputs.explicit_upgrade }}
       working-directory: ${{ github.workspace }}
       run: |
         ./build/bin/erigon snapshots update-to-new-ver-format --datadir $ERIGON_TESTBED_DATA_DIR
+
+    - name: Print datadir contents after upgrade (for debugging)
+      if: ${{ inputs.explicit_upgrade }}
+      working-directory: ${{ github.workspace }}
+      run: |
+        find $ERIGON_TESTBED_DATA_DIR
 
     - name: Run Erigon, wait sync and check ability to maintain sync
       id: test_step
@@ -131,6 +155,70 @@ jobs:
         name: metric-plots
         path: ${{ github.workspace }}/metrics-${{ env.CHAIN }}-plots*
 
+    # Downgrade + tip-tracking test
+
+    - name: Print datadir contents before downgrade (for debugging)
+      working-directory: ${{ github.workspace }}
+      run: |
+        find $ERIGON_TESTBED_DATA_DIR
+
+    - name: Run the datadir downgrade procedure
+      working-directory: ${{ github.workspace }}
+      run: |
+        ./build/bin/erigon seg reset-to-old-ver-format --datadir $ERIGON_TESTBED_DATA_DIR
+
+    - name: Print datadir contents after downgrade (for debugging)
+      working-directory: ${{ github.workspace }}
+      run: |
+        find $ERIGON_TESTBED_DATA_DIR
+
+    - name: Run previous Erigon version, wait sync and check ability to maintain sync
+      id: downgrade_test_step
+      run: |
+        set +e # Disable exit on error
+        
+        # Launch the testbed Erigon instance & test its ability to maintain sync
+        python3 $ERIGON_QA_PATH/test_system/qa-tests/tip-tracking/run_and_check_tip_tracking.py \
+          ${{ env.ERIGON_TESTBED_DATA_DIR }}/../ $ERIGON_TESTBED_DATA_DIR $TRACKING_TIME_SECONDS $TOTAL_TIME_SECONDS Erigon3 $CHAIN
+        
+        # Capture monitoring script exit status
+        test_exit_status=$?
+        
+        # Save the subsection reached status
+        echo "test_executed=true" >> $GITHUB_OUTPUT
+        
+        # Clean up Erigon process if it's still running
+        if kill -0 $ERIGON_PID 2> /dev/null; then
+          echo "Terminating Erigon"
+          kill $ERIGON_PID
+          wait $ERIGON_PID
+        fi
+
+        # Check test runner script exit status
+        if [ $test_exit_status -eq 0 ]; then
+          echo "Downgrade & tip-tracking test completed successfully"
+          echo "::notice::Downgrade & tip-tracking test completed successfully"
+          echo "TEST_RESULT=success" >> "$GITHUB_OUTPUT"
+        else
+          echo "Downgrade tests encountered an error"
+          echo "::error::Downgrade & tip-tracking test encountered an error"
+          echo "TEST_RESULT=failure" >> "$GITHUB_OUTPUT"
+        fi
+
+    - name: Upload Downloader Torrent Client Status of the downgrade test
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: torrent-client-status-downgrade-test
+        path: torrent-client-status.txt
+
+    - name: Upload erigon log of the downgrade test
+      if: steps.downgrade_test_step.outputs.test_executed == 'true'
+      uses: actions/upload-artifact@v4
+      with:
+        name: erigon-log-downgrade-test
+        path: ${{ env.ERIGON_TESTBED_DATA_DIR }}/logs/erigon.log
+
     - name: Delete Erigon Testbed Data Directory
       if: ${{ always() }}
       run: |
@@ -143,12 +231,11 @@ jobs:
       run: |
         python3 $ERIGON_QA_PATH/test_system/db-producer/resume_production.py || true
 
-    - name: Action for Success
-      if: steps.test_step.outputs.TEST_RESULT == 'success'
-      run: echo "::notice::Tests completed successfully"
-
     - name: Action for Not Success
-      if: steps.test_step.outputs.TEST_RESULT != 'success'
+      if: ${{ always() }}
       run: |
-        echo "::error::Error detected during tests"
-        exit 1
+        if [[ "${{ steps.test_step.outputs.TEST_RESULT }}" != "success" ]] || \
+           [[ "${{ steps.downgrade_test_step.outputs.TEST_RESULT }}" != "success" ]]; then
+          echo "::error::Error detected during tests"
+          exit 1
+        fi
