add pre-sync step to stabilise test

diff --git a/.github/workflows/qa-tip-tracking-gnosis.yml b/.github/workflows/qa-tip-tracking-gnosis.yml
--- a/.github/workflows/qa-tip-tracking-gnosis.yml
+++ b/.github/workflows/qa-tip-tracking-gnosis.yml
@@ -45,6 +45,39 @@ jobs:
       run: |
         python3 $ERIGON_QA_PATH/test_system/db-producer/pause_production.py || true
 
+    - name: Run previous Erigon version and wait for sync (stabilization step)
+      id: pre_test_step
+      run: |
+        set +e # Disable exit on error
+        
+        # Launch the testbed Erigon instance & test its ability to maintain sync for 2 minutes
+        python3 $ERIGON_QA_PATH/test_system/qa-tests/tip-tracking/run_and_check_tip_tracking.py \
+          ${{ env.ERIGON_REFERENCE_DATA_DIR }}/../ $ERIGON_REFERENCE_DATA_DIR 120 $TOTAL_TIME_SECONDS Erigon3 $CHAIN
+        
+        # Capture monitoring script exit status
+        test_exit_status=$?
+        
+        # Save the subsection reached status
+        echo "test_executed=true" >> $GITHUB_OUTPUT
+        
+        # Clean up Erigon process if it's still running
+        if kill -0 $ERIGON_PID 2> /dev/null; then
+          echo "Terminating Erigon"
+          kill $ERIGON_PID
+          wait $ERIGON_PID
+        fi
+        # Check test runner script exit status
+        if [ $test_exit_status -eq 0 ]; then
+          echo "Pre-sync step completed successfully"
+          echo "::notice::Pre-sync step completed successfully"
+          echo "TEST_RESULT=success" >> "$GITHUB_OUTPUT"
+        else
+          echo "Pre-sync step encountered an error"
+          echo "::error::Pre-sync step encountered an error"
+          echo "TEST_RESULT=failure" >> "$GITHUB_OUTPUT"
+          exit 1
+        fi
+
     - name: Restore Erigon Testbed Data Directory & Erigon binary
       id: save_chaindata_step
       run: |
@@ -78,9 +111,7 @@ jobs:
       run: |
         set +e # Disable exit on error
         
-        # 1. Launch the testbed Erigon instance
-        # 2. Allow time for the Erigon to achieve synchronization
-        # 3. Begin timing the duration that Erigon maintains synchronization
+        # Launch the testbed Erigon instance & test its ability to maintain sync
         python3 $ERIGON_QA_PATH/test_system/qa-tests/tip-tracking/run_and_check_tip_tracking.py \
           ${{ github.workspace }}/build/bin $ERIGON_TESTBED_DATA_DIR $TRACKING_TIME_SECONDS $TOTAL_TIME_SECONDS Erigon3 $CHAIN
   
@@ -99,10 +130,12 @@ jobs:
 
         # Check test runner script exit status
         if [ $test_exit_status -eq 0 ]; then
-          echo "Tests completed successfully"
+          echo "Upgrade & tip-tracking test completed successfully"
+          echo "::notice::Upgrade & tip-tracking test completed successfully"
           echo "TEST_RESULT=success" >> "$GITHUB_OUTPUT"
         else
-          echo "Error detected during tests"
+          echo "Upgrade & tip-tracking test encountered an error"
+          echo "::error::Upgrade & tip-tracking test encountered an error"
           echo "TEST_RESULT=failure" >> "$GITHUB_OUTPUT"
         fi
 
