Merge erigon main into working version of arbitrum (#18258)
Signed-off-by: jishudashen <jishudashen@foxmail.com>
Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: xinhangzhou <shuangcui@aliyun.com>
Signed-off-by: LesCyber <andi4cing@gmail.com>
Signed-off-by: fengyuchuanshen <fengyuchuanshen@outlook.com>
Signed-off-by: pingshuijie <pingshuijie@outlook.com>
Co-authored-by: antonis19 <antonis19@mail.com>
Co-authored-by: antonis19 <antonis19@users.noreply.github.com>
Co-authored-by: Alex Sharov <AskAlexSharov@gmail.com>
Co-authored-by: Andrew Ashikhmin <34320705+yperbasis@users.noreply.github.com>
Co-authored-by: lupin012 <58134934+lupin012@users.noreply.github.com>
Co-authored-by: Fibonacci747 <albertofibonacci12@gmail.com>
Co-authored-by: awskii <awskii@users.noreply.github.com>
Co-authored-by: Matt Joiner <anacrolix@gmail.com>
Co-authored-by: Michelangelo Riccobene <michelangelo.riccobene@gmail.com>
Co-authored-by: Somnath <snb895@outlook.com>
Co-authored-by: canepat <16927169+canepat@users.noreply.github.com>
Co-authored-by: sudeepdino008 <sudeepdino008@gmail.com>
Co-authored-by: milen <94537774+taratorio@users.noreply.github.com>
Co-authored-by: Ilya Mikheev <54912776+JkLondon@users.noreply.github.com>
Co-authored-by: JkLondon <me@ilyamikheev.com>
Co-authored-by: Bartosz Zawistowski <39065214+bzawisto@users.noreply.github.com>
Co-authored-by: MozirDmitriy <dmitriymozir@gmail.com>
Co-authored-by: lystopad <oleksandr.lystopad@erigon.tech>
Co-authored-by: jishudashen <jishudashen@foxmail.com>
Co-authored-by: Nikita Ostroukhov <gnz.corp@gmail.com>
Co-authored-by: Galoretka <galoretochka@gmail.com>
Co-authored-by: blxdyx <125243069+blxdyx@users.noreply.github.com>
Co-authored-by: blxdyx <blxdyx@users.noreply.github.com>
Co-authored-by: Snezhkko <snezhkodaria38@gmail.com>
Co-authored-by: Giulio rebuffo <giulio.rebuffo@gmail.com>
Co-authored-by: Paweł Bylica <pawel@ethereum.org>
Co-authored-by: Kewei <kewei.train@gmail.com>
Co-authored-by: Bashmunta <georgebashmunta@gmail.com>
Co-authored-by: Mark Holt <135143369+mh0lt@users.noreply.github.com>
Co-authored-by: mholt-dv <mark.holt@distributed.vision>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: alex <alex@alexs-MacBook-Pro.local>
Co-authored-by: Shoham Chakraborty <shhmchk@gmail.com>
Co-authored-by: RealMaxing <realmaxxinn@proton.me>
Co-authored-by: Willian Mitsuda <wmitsuda@gmail.com>
Co-authored-by: Michele Modolo <70838029+michelemodolo@users.noreply.github.com>
Co-authored-by: xinhangzhou <123058040+xinhangzhou@users.noreply.github.com>
Co-authored-by: yperbasis <andrey.ashikhmin@gmail.com>
Co-authored-by: LesCyber <167666635+LesCyber@users.noreply.github.com>
Co-authored-by: Alleysira <56925051+Alleysira@users.noreply.github.com>
Co-authored-by: fengyuchuanshen <fengyuchuanshen@outlook.com>
Co-authored-by: Torprius <torrpriius@gmail.com>
Co-authored-by: Ping Shuijie <pingshuijie@outlook.com>
Co-authored-by: Forostovec <ilonaforostovec22@gmail.com>
Co-authored-by: Bartosz Zawistowski <bartosz.zawistowski@erigon.tech>
Co-authored-by: awskii <artem.tsskiy@gmail.com>
Co-authored-by: JkLondon <ilya@mikheev.fun>

diff --git a/.github/workflows/test-hive.yml b/.github/workflows/test-hive.yml
--- a/.github/workflows/test-hive.yml
+++ b/.github/workflows/test-hive.yml
@@ -5,7 +5,6 @@ on:
     branches:
         - main
         - 'release/**'
-        - docker_pectra
   schedule:
     - cron: "0 05 * * *" # daily at 5 am UTC
   workflow_dispatch:
@@ -16,16 +15,16 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Hive
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
         with:
           repository: ethereum/hive
           # ref: master
           path: hive
 
       - name: Setup go env and cache
-        uses: actions/setup-go@v5
+        uses: actions/setup-go@v6
         with:
-          go-version: '>=1.23'
+          go-version: '>=1.24'
           go-version-file: 'hive/go.mod'
 
       - name: Login to Docker Hub
@@ -53,10 +52,16 @@ jobs:
         run: |
           cd hive
           run_suite() {
+            if [ $# -ne 3 ]; then
+              echo "Error: run_suite requires exactly 3 parameters"
+              echo "Usage: run_suite <sim> <sim.limit> <max_allowed_failures>"
+              echo "Provided: $# parameters"
+              exit 1
+            fi
             echo -e "\n\n============================================================"
             echo "Running test: ${1}-${2}"
             echo -e "\n"
-            ./hive --sim ethereum/"${1}" --sim.limit="${2}" --client erigon 2>&1 | tee output.log || {
+            ./hive -docker.auth --sim ethereum/"${1}" --sim.limit="${2}" --client erigon 2>&1 | tee output.log || {
               if [ $? -gt 0 ]; then
                 echo "Exitcode gt 0"
               fi
@@ -80,18 +85,21 @@ jobs:
               echo "failed" > failed.log
               exit 1
             fi
-            if (( failed*10 > tests )); then
+            max_allowed_failures="${3}"
+            if (( failed > max_allowed_failures )); then
               echo "Too many failures for suite ${1}-${2} - ${failed} failed out of ${tests}"
               echo "failed" > failed.log
               exit 1
             fi
           }
-          run_suite engine exchange-capabilities 
-          run_suite engine withdrawals
-          run_suite engine cancun
-          run_suite engine api
-          # run_suite engine auth
-          # run_suite rpc compat
+          run_suite engine exchange-capabilities 0
+          run_suite engine withdrawals 0
+          run_suite engine cancun 0
+          run_suite engine api 0
+          # 3 failures out of 8 tests at time of writing
+          run_suite engine auth 3
+          # 100 failures out of 190 tests at time of writing
+          run_suite rpc compat 100
         continue-on-error: true
 
       - name: Upload output log
